services:
  - type: web
    name: ultraship-backend
    env: node
    rootDirectory: ultraship-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
